- include: centos.yml
  when:
    ansible_os_family: 'RedHat'

- include: ubuntu.yml
  when:
    ansible_os_family: 'Debian'

- name: start zookeeper
  service:
    name: zookeeper
    state: started
    enabled: yes
