---
- name: Install ZooKeeper
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zookeeper
    - zookeeperd

- name: config zookeeper
  template: src={{ item }}.j2 dest=/etc/alternatives/zookeeper-conf/{{ item }}
  with_items:
    - myid
    - zoo.cfg
    - log4j.properties
    - zookeeper-env.sh
