- name: add sudo users
  user:
    name: "{{ item['username'] }}"
    groups: sudo
  with_items: "{{ sudo_users }}"
  tags:
    - users

- name: Allow sudo users to nopasswd
  template:
    src: sudo.j2
    dest: /etc/sudoers.d/sudo
    mode: 0440
    owner: root
    group: root
    backup: yes
  tags:
    - users
